In [1]:
import numpy as np
import pandas as pd

In [3]:
#Question 1&2
print(np.__version__)
print(pd.__version__)

1.18.5
1.0.5


In [8]:
df = pd.read_csv('data.csv')

In [10]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
#Question 3
#get the average price of BMW
df[df['Make'] == 'BMW'].MSRP.mean()

61546.76347305389

In [12]:
#Question 4
#get how many null records at engine hp field since 2015
df_15 = df[df['Year'] >= 2015]
df_15['Engine HP'].isnull().sum()

51

In [13]:
# Question 5
#get the mean of engine hp before filling nulls before
round(df['Engine HP'].mean())

249

In [19]:
df_filled = df['Engine HP'].fillna(df['Engine HP'].mean())
df_filled.isnull().sum()

0

In [21]:
#get the mean of engine hp after filling nulls with column mean
# we could notice they are the same 
round(df_filled.mean())

249

In [22]:
#Question 6
df_rr = df[df['Make'] == 'Rolls-Royce']
df_rr = df_rr[['Engine HP','Engine Cylinders','highway MPG']]
df_rr.drop_duplicates(inplace=True)
df_rr

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [26]:
X = df_rr.values

In [27]:
XTX=np.dot(X.T,X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [28]:
XTX.sum()

1970887.0

In [30]:
#Question 7
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [32]:
r = np.dot(np.linalg.inv(XTX),X.T)
w = np.dot(r,y)
w

array([ 0.19989598, 31.02612262, 31.65378877])